### ISSUE TITLE
pnpm run dev跑起来白屏报错

### ISSUE THREAD

**Issue by ShipinZ** [dromara/yft-design#102]
我clone下main分支的代码，执行`pnpm install`。下载完依赖后通过`pnpm run dev`运行，浏览器访问会白屏，控制台信息如下：
![image](https://github.com/user-attachments/assets/22243da4-a49b-4254-be11-19bfdc671c96)
这是error部分的信息：
```
main.ts:27  TypeError: Cannot read properties of null (reading 'getActiveObject')
    at Proxy.currentTemplateElement (template.ts:62:35)
    at ComputedRefImpl.fn (pinia.mjs:1258:38)
    at refreshComputed (reactivity.esm-bundler.js:377:28)
    at get value (reactivity.esm-bundler.js:1627:5)
    at MutableReactiveHandler.get (reactivity.esm-bundler.js:963:61)
    at propertyToRef (reactivity.esm-bundler.js:1563:15)
    at toRef (reactivity.esm-bundler.js:1557:12)
    at storeToRefs (pinia.mjs:1970:21)
    at default (useHandleTemplate.ts:19:57)
    at setup (EditorPool.vue:144:1)
triggerError @ vue-router.mjs:3596
(匿名) @ vue-router.mjs:3633
Promise.catch
handleScroll @ vue-router.mjs:3633
finalizeNavigation @ vue-router.mjs:3479
(匿名) @ vue-router.mjs:3343
Promise.then
pushWithRedirect @ vue-router.mjs:3310
push @ vue-router.mjs:3235
install @ vue-router.mjs:3677
use @ runtime-core.esm-bundler.js:3826
start @ main.ts:27
await in start
(匿名) @ main.ts:36
显示 9 更多框架
显示简略信息

template.ts:62  Uncaught (in promise) TypeError: Cannot read properties of null (reading 'getActiveObject')
    at Proxy.currentTemplateElement (template.ts:62:35)
    at ComputedRefImpl.fn (pinia.mjs:1258:38)
    at refreshComputed (reactivity.esm-bundler.js:377:28)
    at get value (reactivity.esm-bundler.js:1627:5)
    at MutableReactiveHandler.get (reactivity.esm-bundler.js:963:61)
    at propertyToRef (reactivity.esm-bundler.js:1563:15)
    at toRef (reactivity.esm-bundler.js:1557:12)
    at storeToRefs (pinia.mjs:1970:21)
    at default (useHandleTemplate.ts:19:57)
    at setup (EditorPool.vue:144:1)
currentTemplateElement @ template.ts:62
(匿名) @ pinia.mjs:1258
refreshComputed @ reactivity.esm-bundler.js:377
get value @ reactivity.esm-bundler.js:1627
get @ reactivity.esm-bundler.js:963
propertyToRef @ reactivity.esm-bundler.js:1563
toRef @ reactivity.esm-bundler.js:1557
storeToRefs @ pinia.mjs:1970
default @ useHandleTemplate.ts:19
setup @ EditorPool.vue:144
callWithErrorHandling @ runtime-core.esm-bundler.js:199
setupStatefulComponent @ runtime-core.esm-bundler.js:7870
setupComponent @ runtime-core.esm-bundler.js:7831
mountComponent @ runtime-core.esm-bundler.js:5179
processComponent @ runtime-core.esm-bundler.js:5145
patch @ runtime-core.esm-bundler.js:4663
mountChildren @ runtime-core.esm-bundler.js:4895
mountElement @ runtime-core.esm-bundler.js:4818
processElement @ runtime-core.esm-bundler.js:4783
patch @ runtime-core.esm-bundler.js:4651
mountChildren @ runtime-core.esm-bundler.js:4895
mountElement @ runtime-core.esm-bundler.js:4818
processElement @ runtime-core.esm-bundler.js:4783
patch @ runtime-core.esm-bundler.js:4651
componentUpdateFn @ runtime-core.esm-bundler.js:5289
run @ reactivity.esm-bundler.js:222
setupRenderEffect @ runtime-core.esm-bundler.js:5417
mountComponent @ runtime-core.esm-bundler.js:5192
processComponent @ runtime-core.esm-bundler.js:5145
patch @ runtime-core.esm-bundler.js:4663
mountChildren @ runtime-core.esm-bundler.js:4895
mountElement @ runtime-core.esm-bundler.js:4818
processElement @ runtime-core.esm-bundler.js:4783
patch @ runtime-core.esm-bundler.js:4651
componentUpdateFn @ runtime-core.esm-bundler.js:5289
run @ reactivity.esm-bundler.js:222
setupRenderEffect @ runtime-core.esm-bundler.js:5417
mountComponent @ runtime-core.esm-bundler.js:5192
processComponent @ runtime-core.esm-bundler.js:5145
patch @ runtime-core.esm-bundler.js:4663
mountChildren @ runtime-core.esm-bundler.js:4895
mountElement @ runtime-core.esm-bundler.js:4818
processElement @ runtime-core.esm-bundler.js:4783
patch @ runtime-core.esm-bundler.js:4651
mountChildren @ runtime-core.esm-bundler.js:4895
mountElement @ runtime-core.esm-bundler.js:4818
processElement @ runtime-core.esm-bundler.js:4783
patch @ runtime-core.esm-bundler.js:4651
componentUpdateFn @ runtime-core.esm-bundler.js:5289
run @ reactivity.esm-bundler.js:222
setupRenderEffect @ runtime-core.esm-bundler.js:5417
mountComponent @ runtime-core.esm-bundler.js:5192
processComponent @ runtime-core.esm-bundler.js:5145
patch @ runtime-core.esm-bundler.js:4663
mountChildren @ runtime-core.esm-bundler.js:4895
processFragment @ runtime-core.esm-bundler.js:5075
patch @ runtime-core.esm-bundler.js:4637
componentUpdateFn @ runtime-core.esm-bundler.js:5289
run @ reactivity.esm-bundler.js:222
setupRenderEffect @ runtime-core.esm-bundler.js:5417
mountComponent @ runtime-core.esm-bundler.js:5192
processComponent @ runtime-core.esm-bundler.js:5145
patch @ runtime-core.esm-bundler.js:4663
componentUpdateFn @ runtime-core.esm-bundler.js:5289
run @ reactivity.esm-bundler.js:222
setupRenderEffect @ runtime-core.esm-bundler.js:5417
mountComponent @ runtime-core.esm-bundler.js:5192
processComponent @ runtime-core.esm-bundler.js:5145
patch @ runtime-core.esm-bundler.js:4663
componentUpdateFn @ runtime-core.esm-bundler.js:5369
run @ reactivity.esm-bundler.js:222
runIfDirty @ reactivity.esm-bundler.js:260
callWithErrorHandling @ runtime-core.esm-bundler.js:199
flushJobs @ runtime-core.esm-bundler.js:408
显示 71 更多框架
显示简略信息

localhost/:1  Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
```

**Comment by more-strive** [comment]
刚提交代码修复了这个问题，可以git pull在试试看

**Comment by ShipinZ** [comment]
解决了，非常感谢，这就是中国速度嘛

**Comment by more-strive** [comment]
没问题就关闭了哈
